import Homefeed from './HomeFeed';
import Notification from './Notification';
import Settings from './Settings';
import Search from './Search';
import Profile from './Profile';
import Post from './Post';
import NewsListScreen from './Newslist';
import Getintotouch from './Getintotouch';
import Aboutus from './Aboutus';
export {Homefeed, Notification,Getintotouch,Aboutus, Search, Settings, Profile, Post,NewsListScreen};
